development:
  APP_HOST: 'localhost:3000' # e.g. osb.mydomain.com
  APP_PROTOCOL: 'http'

  ACTIVEMERCHANT_BILLING_MODE: "test"

  PAYPAL:
    PAYPAL_URL: https://www.sandbox.paypal.com/cgi-bin/webscr?
    PAYPAL_LOGIN: paypallogin@paypal.com
    PAYPAL_PASSWORD: paypalpassword
    PAYPAL_SIGNATURE: AFcWxV21C7fd0v3bYYYRCpSSRl31AvdaH-JlMzh6jMIiXfnDp2DVt9sQ
    PAYPAL_BUSINESS: suneel.kumar-facilitator@phaedrasolutions.com

  WKHTMTTOPDF_PATH: /home/umair/.rvm/gems/ruby-2.0.0-p598@osb_live/bin/wkhtmltopdf

  SMTP_SETTING:
    address: localhost
    port: 1025


  ENCRYPTION_KEY: "ENTER-YOUR-ENCRYPTED-KEY-HERE"


production:
   APP_HOST: 'localhost:3000' # e.g. osb.mydomain.com
   APP_PROTOCOL: 'http'

   ACTIVEMERCHANT_BILLING_MODE: "test"

   PAYPAL:
     PAYPAL_URL: 'https://www.sandbox.paypal.com/cgi-bin/webscr?'
     PAYPAL_LOGIN: 'umair.munir-facilitator_api1.nxb.com.pk'
     PAYPAL_PASSWORD: 'QR3FZ5MS69454MER'
     PAYPAL_SIGNATURE: 'AFcWxV21C7fd0v3bYYYRCpSSRl31AvdaH-JlMzh6jMIiXfnDp2DVt9sQ'
     PAYPAL_BUSINESS: 'onlyforarif-facilitator@gmail.com'
   WKHTMTTOPDF_PATH: '/home/umair/.rvm/gems/ruby-2.0.0-p598@osb_live/bin/wkhtmltopdf' # the location where wkhtmltopdf is installed

   SMTP_SETTING:
     address: "localhost"
     port: 1080
     domain: "gmail"
     authentication: :plain
     enable_starttls_auto: true
     user_name:
     password:

   ENCRYPTION_KEY: "ENTER-YOUR-ENCRYPTED-KEY-HERE"